### ISSUE TITLE
Discrepancy between the paper and the implementation? 

### ISSUE THREAD

**Issue by tonyswoo** [guolinke/TUPE#12]
Hi, 

First of all, thank you for your amazing work; the paper was quite an interesting read. 

I just noticed an inconsistency between the paper and the implementation (specifically, in the reset part), and I was hoping you could clear it up. 

![image](https://user-images.githubusercontent.com/32477980/118495708-6ab52f80-b75e-11eb-8596-283c58c4a2b6.png)

According to the paper, the positional attention (or positional correlation, in your terms) is "reset" to θ1 or θ2, if the token attending or being attended is the [CLS] token. 

![image](https://user-images.githubusercontent.com/32477980/118495518-38a3cd80-b75e-11eb-999a-27c27e11bcad.png)

In the appendix, you provide the definition of the θ values; you essentially have pθ1 and pθ2, which are treated like absolute positional embeddings (as in, they are multiplied by the same query/key matrices as absolute positional embeddings) attending to themselves.

However, in your implementation, you seem to be "resetting" the absolute and the relative correlations separately: 

https://github.com/guolinke/TUPE/blob/10ecb61675cd5866f47d2f8e5cedf944c66de5be/fairseq/modules/transformer_sentence_encoder.py#L181-L184
https://github.com/guolinke/TUPE/blob/10ecb61675cd5866f47d2f8e5cedf944c66de5be/fairseq/modules/transformer_sentence_encoder.py#L239-L240

which would mean that there is another bias term added to the equation above. 

Could you explain the reasoning behind this change, and how significant (or insignificant) of a change this is to the overall performance?

**Comment by guolinke** [comment]
Yeah, it indeed is slightly different. 
In the implementation, we reset the abs-pos and rel-pos separately, by their own forms. 
I think it is almost the same as reset them unified, as the difference is a bias term (from rel-pos part).
This is for easier implementation, and make codes cleaner.

**Comment by tonyswoo** [comment]
That makes sense. 

Thank you very much for your time.
