### ISSUE TITLE
The first column of `dict.txt` is equivalent to the vocabulary learned from fastBPE?

### ISSUE THREAD

**Issue by huberemanuel** [guolinke/TUPE#16]
In other words, can I use `dict.txt` first column as the vocabulary and their respective line number as the id for projecting the input tokens to the embedding layer?

**Comment by guolinke** [comment]
yeah, the first column is the subword. 
However, you need to split words into subwords, this process is done by fastBPE.
Then the text data can map to subwords, and then you can use line numbers for embedding layer.

**Comment by huberemanuel** [comment]
Perfect, thank you!
