### ISSUE TITLE
How to set up input for sentence classification task?

### ISSUE THREAD

**Issue by huberemanuel** [guolinke/TUPE#19]
Debugging the fine-tuning code I saw that it adds a token with id 0 at the beginning of each sentence and a token with id 2 at the end of each sentence, I assume they are the beginning and end of sentence tokens. From what I read in the paper I don't need to add the CLS token and the code doesn't seem to do that either, so the next step is to pass the tokens through the network where I'll have a tensor with the shape [batch_size, tokens_len, features_size], to make the classification of a sentence, do I use the feature of the first token of the sentence?

Example:
```py
model_output = model(input_tensor) # model_output.shape [batch_size, tokens_len, features_size]
input_to_classification = model_output[:,0,:] # input_to_classification.shape [batch_size, 1, features_size]
classification = cls_model(input_to_classification) 
```

I know that the current fine-tuning already does all of this process, but I would like to use the available model with my own sentence classification algorithm. Therefore, I need to reproduce some of the steps done by fairseq.

**Comment by guolinke** [comment]
they are set up in task in fairseq.
for example: https://github.com/guolinke/TUPE/blob/4c64ff748a7039be4918429f05bbb43d81357107/fairseq/tasks/sentence_prediction.py#L118-L127

I think you need to write your own task for your own purpose.

**Comment by huberemanuel** [comment]
Thank you, Guolin! This code snippet helped me to understand better. I wrote an example of usage based on your comment, and I hope it helps further users.

```py
import fastBPE

# consts
s_begin = 0
s_end = 2
pad = 1
unk = 3

batch_size = 32
max_len = 512

# load model and resources
model = checkpoint_utils.load_model_ensemble(["path/to/tupe_ckp"], {"data": ""path/to/tupe_ckp""})[0][0]
bpe = fastBPE.fastBPE("path/to/tupe_ckp/bpe-code")
with open("path/to/tupe_ckp/dict.txt") as dict_f:
    content = dict_f.readlines()
    vocab_dict = {v.split(" ")[0]: k for k, v in enumerate(content)}

# read your dataset and process each batch with the following code
src_tokens = np.zeros((batch_size, max_len))
src_lengths = np.zeros((batch_size, 1))
 
for i, sent in enumerate(sentences):
    word_tokens = bpe.apply(sent) # sent being a list of tokens List[str]
    # Text to vocab indexes
    word_tokens = [vocab_dict.get(x, unk) for x in word_tokens]
    # insert sentence begin and end tokens
    word_tokens = [s_begin] + word_tokens + [s_end]
    src_lengths[i] = len(word_tokens) 
    # add padding 
    word_tokens = np.concatenate([word_tokens, np.ones(max_len - len(word_tokens))]
    src_tokens[i] = word_tokens

# With the formatted input batch, run the forward on the TUPE model.

sample = {
    "src_tokens": torch.tensor(src_inputs).cuda(),
    "src_lengths": torch.tensor(src_lenghts).cuda(),
}

features, _ = model(**sample, features_only=True)

# Your classification network input is ready :)
```
