### ISSUE TITLE
About the reset function in attention bias

### ISSUE THREAD

**Issue by Erutan-pku** [guolinke/TUPE#4]
In  transformer_sentence_encoder.py line 233~238 : 

`        # p_0 \dot p_0 is cls to others
        cls_2_other = abs_pos_bias[:, 0, 0]
        # p_1 \dot p_1 is others to cls
        other_2_cls = abs_pos_bias[:, 1, 1]
        # offset 
        abs_pos_bias = abs_pos_bias[:, 1:, 1:]`

abs_pos_bias[:, 1, 1] seems strange. I think this should be abs_pos_bias[:, 1, 0] ?

**Comment by guolinke** [comment]
(0,0)=p0 \dot p0,
(1,1)=p1 \dot p1,
p0 and p1 are embedding for cls to others and others to cls

**Comment by Erutan-pku** [comment]
Oh, It seems that you have TWO additional tokens before the sentence, at p0 and p1, including the [CLS] token. 
Then you truncate the attention about the first token (line 238), using the attention between p0 and p0 and attention between p1 and p1 for cls to others and others to cls, respectively? (line 239~240)

**Comment by guolinke** [comment]
refer the the our description in the paper:
![image](https://user-images.githubusercontent.com/16040950/93898536-e5d85a00-fd25-11ea-9993-ae17fadf4c8e.png)

**Comment by Erutan-pku** [comment]
Oh, I miss that. Thank you!

**Comment by d-li14** [comment]
@guolinke Hi, I still wonder why the p0 \dot p0 and p1 \dot p1 is reused here. What if other position encoding vectors, such as p2 \dot p2 and p3 \dot p3? And what if using completely irrelevant vectors, such as q0 ]dot q0 and q1 \dot q1?
