### ISSUE TITLE
Could you please point out the CORE code for TUPE for study? As there are too many fairseq code.

### ISSUE THREAD

**Issue by guotong1988** [guolinke/TUPE#6]
Thank you very much.

**Comment by guolinke** [comment]
refer to https://github.com/guolinke/TUPE#brief-introduction

> Our implementation is based on fairseq, with several changes:

> update fairseq/modules/transformer_sentence_encoder.py and fairseq/modules/multihead_attention.py for untied positional encoding.
> some other minor changes to support max-epoch with warmup-ratio in finetune, instead of setting different total-num-update and warmup-updates for different tasks.
